symbol: "AAPL"
start_date: "2021-06-28"
end_date: "2025-06-28"
initial_balance: 10000

actions:
  0: "HOLD"
  1: "BUY"
  2: "SELL"

training:
  episodes: 500
  batch_size: 32
  gamma: 0.95
  epsilon: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  learning_rate: 0.001

model:
  state_size: 4
  action_size: 3
  hidden_layers: [64, 64]