symbol: 'DELL'
start_date: '2020-01-01'
end_date: '2025-01-01'
initial_balance: 10000

actions:
  0: 'HOLD'
  1: 'BUY'
  2: 'SELL'

training:
  episodes: 1000
  batch_size: 32
  gamma: 0.95
  epsilon: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  learning_rate: 0.001
  max_memory_size: 2000

model:
  state_size: 4
  hidden_layers: [64, 64]
  model_path: './results/dqn_trading_model.pth'